// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzyxcwddaksonybcmwda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6eXhjd2RkYWtzb255YmNtd2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDc1ODEsImV4cCI6MjA1OTQ4MzU4MX0.Mhz249mldGYk9jLtj6W3lyrVHZalhA48z2pRwyvogE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);